# -*- coding: utf-8 -*-
"""FlaskApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2Roa6N30OoSiyZ_vOpF-m3xQaoHah4r
"""

from flask import Flask, request, jsonify
import joblib
import os

app = Flask(__name__)

"""load model"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Load from exact path
model = joblib.load("/content/drive/MyDrive/crop_model.joblib")

@app.route('/predict', methods=['POST'])
def predict():
    try:
        data = request.json
        required = ["N", "P", "K", "ph", "humidity", "temperature"]
        if not all(key in data for key in required):
            return jsonify({"error": "Missing fields"}), 400

        features = [data[key] for key in required]
        prediction = model.predict([features])[0]
        return jsonify({"crop": prediction})

    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)